[project]
name = "MSA"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.115.1so2",
    "numpy",
]

[tool.ux]
venv = "MSA"
